# Generated by Django 5.2.4 on 2025-07-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0017_tbl_house'),
        ('User', '0012_remove_tbl_cart_house_remove_tbl_cart_userid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_house',
        ),
    ]
