# Generated by Django 5.2.4 on 2025-07-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='house',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='userid',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
